[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]==1.9.1",
    "scrapy==2.13.0",
    "beautifulsoup4==4.13.4",
]
